[build]
  # Directory to change to before starting a build
  base = "frontend/"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist/"
  
  # Build command with error handling
  command = "npm ci --legacy-peer-deps && npm run build"

[build.environment]
  # Node.js version - using 18 for better stability
  NODE_VERSION = "18"
  # Node options for better memory management
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Environment settings
  NODE_ENV = "production"
  # NPM configuration
  NPM_CONFIG_PRODUCTION = "false"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (you'll need to set these in Netlify dashboard)
# VITE_API_URL = "https://your-backend-url.com"
# VITE_ENVIRONMENT = "production"